### ISSUE TITLE
Some little help 

### ISSUE THREAD

**Issue by francesco2013** [igdb/igdb-api-php#1]
Could you please show me some examples ?

I have my IGDB API key I need to search in PHP by game name and I need the following information:

- Game Name
- Short Description
- Long Description
- Category
- Developer
- Publisher
- Score
- Release Date

Thank you in advance.

I look forward to hearing from you.

Regards,

Francesco Fazio

**Comment by krazyjakee** [comment]
Hi there,

1. Download the class and change the API_KEY to your own.
2. `require` it in your project.
3. Access it like `IGDB::gamesIndex($opts, $callback)`
4. The options and responses are covered in the documentation here: https://www.igdb.com/api/v1/documentation

**Comment by francesco2013** [comment]
Hi Jake,

Look I have tried I get:

root@web:/var/www/playstationweb/html# php igdb-test.php
PHP Notice:  Undefined variable: result in
/var/www/playstationweb/html/igdb-test.php on line 7
PHP Notice:  Undefined variable: endpoint in
/var/www/playstationweb/html/igdb-class.php on line 6
PHP Notice:  Undefined variable: apikey in
/var/www/playstationweb/html/igdb-class.php on line 24
PHP Warning:  file_get_contents(games): failed to open stream: No such file
or directory in /var/www/playstationweb/html/igdb-class.php on line 28
PHP Fatal error:  Function name must be a string in
/var/www/playstationweb/html/igdb-class.php on line 29

Here is my test code in php:

root@web:/var/www/playstationweb/html# cat igdb-test.php
<?php

require("igdb-class.php");


IGDB::gamesIndex("name='Alien: Isolation'", $result);

echo $result;


?>

I have added my API key in the class file:

<?php
class IGDB{
  private $apikey = "hAQr3Ul8Yym0vVzOjGabaqZapSP3ofp3SPTPCmViNxs";
  private $endpoint = "https://www.igdb.com/api/v1/";
  private function request($url, $callback, $opts = false){
    $url = $endpoint . $url;
    if($opts){

--------------------------------------------------------------------------------


I wanna do some simple search by name and get the following data:

- Game Name
- Develper
- Publisher
- Category
- Release Date
- Long Description
- Short Description
- Release Date

I cant figure out how to and the documentation on the IGDB website is
either wrong or outdated.

I have been using API for work for years and I am not a newbie ... It does
not work !

Thanks again for your time man !

Regards,

Francesco Fazio

2016-03-17 10:58 GMT+01:00 Jake Cattrall <notifications@github.com>:

**Comment by francesco2013** [comment]
Also I have noticed this:

https://www.igdb.com/api/v1/games/1979token=hAQr3Ul8Yym0vVzOjGabaqZapSP3ofp3SPTPCmViNxs

This does work and I get the JSON data.

If I search for anything else like:
https://www.igdb.com/api/v1/games/turok?token=hAQr3Ul8Yym0vVzOjGabaqZapSP3ofp3SPTPCmViNxs

This is what I get: {"status":"500","error":"Internal Server Error"}

It is driving me mad really man.

Thanks again.

I hope someone will be able to clarify this and let me understand how this works and how I could search successfully.

Regards,

Francesco Fazio

**Comment by sharpless512** [comment]
Hi,

The games/ only works with the gameID, just like described in the documentation.
https://www.igdb.com/api/v1/documentation/games#games__gameId__get

Im working on solving your other issues right now

**Comment by francesco2013** [comment]
Hi,

Thanks a million man. How do you get the game id if you dont know it ?
I need to search from my site and the only data I know is the game name ..
I would love to be able to know the ID of each game but I need to be able
to find it by name if you know what I mean.

Thanks again !

Regards,

Francesco Fazio

2016-03-17 11:49 GMT+01:00 Sharpless512 <notifications@github.com>:

**Comment by francesco2013** [comment]
So this way to search does not work ?

https://www.igdb.com/api/v1/documentation/games#games_search_get

**Comment by francesco2013** [comment]
One more think I have noticed:

As opposite as it is stated in the documentation of the API if I use the
generic search
https://www.igdb.com/api/v1/games?token=hAQr3Ul8Yym0vVzOjGabaqZapSP3ofp3SPTPCmViNxs

that should return a list of ALL games and their relative IDs I get only
the game with the ID 1. I just need to understand which parameters I need
to be able to obtain the ID of a game from his name and then run a second
API request to get the data of the specific game I look for.

https://www.igdb.com/api/v1/games?token=hAQr3Ul8Yym0vVzOjGabaqZapSP3ofp3SPTPCmViNxs

{"games":[{"id":1,"name":"Thief II: The Metal
Age","slug":"thief-ii-the-metal-age","release_date":"2000-03-21","alternative_name":null},{"id":2,"name":"Thief:
The Dark Project","slug":"thief-the-dark-project","release_date":"1998-11-30","alternative_name":null},{"id":3,"name":"Thief:
Deadly Shadows","slug":"thief-deadly-shadows","release_date":"2004-05-25","alternative_name":null},{"id":4,"name":"Thief","slug":"thief","release_date":"2014-02-25","alternative_name":"Thief
4"},{"id":5,"name":"Baldur's
Gate","slug":"baldur-s-gate","release_date":"1998-11-30","alternative_name":null},{"id":6,"name":"Baldur's
Gate II: Shadows Of
Amn","slug":"baldur-s-gate-ii-shadows-of-amn","release_date":"2000-09-24","alternative_name":null},{"id":7,"name":"Jagged
Alliance","slug":"jagged-alliance","release_date":"1994-06-02","alternative_name":null},{"id":8,"name":"Jagged
Alliance: Deadly
Games","slug":"jagged-alliance-deadly-games","release_date":"1995-01-01","alternative_name":null},{"id":9,"name":"Jagged
Alliance 2","slug":"jagged-alliance-2","release_date":"1999-07-23","alternative_name":null},{"id":10,"name":"Jade
Empire: Special
Edition","slug":"jade-empire-special-edition","release_date":"2005-04-12","alternative_name":null},{"id":11,"name":"Vampire:
The Masquerade -
Bloodlines","slug":"vampire-the-masquerade-bloodlines","release_date":"2004-11-16","alternative_name":null},{"id":12,"name":"Vampire:
The Masquerade -
Redemption","slug":"vampire-the-masquerade-redemption","release_date":"2000-06-07","alternative_name":null},{"id":13,"name":"Fallout","slug":"fallout","release_date":"1997-09-30","alternative_name":null},{"id":14,"name":"Fallout
2","slug":"fallout-2","release_date":"1998-09-30","alternative_name":null},{"id":15,"name":"Fallout
3","slug":"fallout-3","release_date":"2008-10-28","alternative_name":null},{"id":16,"name":"Fallout:
New Vegas","slug":"fallout-new-vegas","release_date":"2010-10-19","alternative_name":null},{"id":17,"name":"Fallout
Tactics: Brotherhood Of
Steel","slug":"fallout-tactics-brotherhood-of-steel","release_date":"2001-03-15","alternative_name":null},{"id":18,"name":"Max
Payne","slug":"max-payne","release_date":"2001-07-23","alternative_name":null},{"id":19,"name":"Max
Payne 2: The Fall Of Max
Payne","slug":"max-payne-2-the-fall-of-max-payne","release_date":"2003-10-24","alternative_name":null},{"id":20,"name":"BioShock","slug":"bioshock","release_date":"2007-08-21","alternative_name":null},{"id":21,"name":"BioShock
2","slug":"bioshock-2","release_date":"2010-02-09","alternative_name":null},{"id":22,"name":"System
Shock 2","slug":"system-shock-2","release_date":"1999-08-11","alternative_name":null},{"id":23,"name":"System
Shock","slug":"system-shock","release_date":"1994-09-22","alternative_name":null},{"id":24,"name":"UFO:
Enemy Unknown","slug":"ufo-enemy-unknown--1","release_date":"1994-01-01","alternative_name":null},{"id":25,"name":"X-COM:
Terror From The
Deep","slug":"x-com-terror-from-the-deep","release_date":"1995-01-01","alternative_name":null}]}

GET /games

Retrieve a list of all games.




2016-03-17 11:53 GMT+01:00 Francesco fazio <ffazio1@gmail.com>:

**Comment by francesco2013** [comment]
Please guys just tell me the URL parameters to get the ID of a game from
the name and that is it. Problem solved. Thanks again a lot.

2016-03-17 12:02 GMT+01:00 Francesco fazio <ffazio1@gmail.com>:

**Comment by sharpless512** [comment]
You can find the ID of the game with the search:

/games/search?q=zelda

**Comment by francesco2013** [comment]
Yes ! Thanks man ! Cool !!!! WORKS !

Love ya ! I wish you an awesome day and the most fantastic incoming weekend
in the history of the UK :)

Thanks again ! I own you a dozen pints each guys :)

When I will be in London next time I am going to mail you and you will be
my guests for the night !

Francesco

2016-03-17 12:10 GMT+01:00 Sharpless512 <notifications@github.com>:

**Comment by sharpless512** [comment]
I have updated the igdb class now

**Comment by francesco2013** [comment]
Thanks mate :) I am really grateful much appreciated. I am serious about
the 12 pints I want to offer you and Jake !

2016-03-17 13:07 GMT+01:00 Sharpless512 <notifications@github.com>:

**Comment by sharpless512** [comment]
Glad we can help :)
