### ISSUE TITLE
Errors in the code

### ISSUE THREAD

**Issue by francesco2013** [igdb/igdb-api-php#2]
Hi,

I dont know if anybody managed to use your code but I think there is something rather wrong:

I have put my IGDB API key (that works for sure) into your class file:

<?php
class IGDB{
  private $apikey = "XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX";
  private $endpoint = "https://www.igdb.com/api/v1/";
  private function request($url, $callback, $opts = false){
    $url = $endpoint . $url;
    if($opts){

----------------------------------

I then  include the class in my php test file:

<?php

include ("igdb-class.php");

$testObject = new IGDB();

$testObject->gamesSearch("name='Alien: Isolation'", $result);

echo $result;

?>

When I run it from the command line I get a mountain of errors:

root@web:/var/www/playstationweb/html# php igdb-test.php
PHP Notice:  Undefined variable: result in /var/www/playstationweb/html/igdb-test.php on line 7
PHP Notice:  Undefined variable: endpoint in /var/www/playstationweb/html/igdb-class.php on line 6
PHP Warning:  Invalid argument supplied for foreach() in /var/www/playstationweb/html/igdb-class.php on line 9
PHP Notice:  Undefined variable: apikey in /var/www/playstationweb/html/igdb-class.php on line 24
PHP Warning:  file_get_contents(games/search?): failed to open stream: No such file or directory in /var/www/playstationweb/html/igdb-class.php on line 28
PHP Fatal error:  Function name must be a string in /var/www/playstationweb/html/igdb-class.php on line 29

Could you please help me understanding what I do wrong ?

Thanks.

Francesco Fazio

**Comment by sharpless512** [comment]
Duplicate: https://github.com/igdb/igdb-api-php/issues/1
