### ISSUE TITLE
Search not working

### ISSUE THREAD

**Issue by sharpless512** [igdb/igdb-api-php#3]
> require("igdb.php");
> $igdb = new IGDB;
> print($igdb->gamesSearch("zelda"))

the igbd.php file from GithHub which deals with 2 parameters:

> public function gamesSearch($query, $parameters = false){ return $this->request('games/search?q=' . $query . $parameters); }

I get this error with php : 

> Warning: file_get_contents(https://www.igdb.com/api/v1/games/search?q=zelda?token=MY_API_KEY : failed to open stream: HTTP request failed! HTTP/1.1 401 Unauthorized in /homepages/30/d585094664/htdocs/panel/membre/include/igdb.php on line 11

TODO: 
Oops, I made a mistake in the code. The correct way should be: /api/v1/games/search?q=zelda&token=

So an & instead of a second ?

**Comment by Darkman75ful** [comment]
I fixed bugs
[https://github.com/igdb/igdb-api-php/commit/e6dbb5999f332344888f6cf4399adbe0279edb2f](url)
